### ISSUE TITLE
Problems with hw decoding and with chromium

### ISSUE THREAD

**Issue by lamiska** [moonlight-stream/moonlight-chrome#100]
Hi, moonlight on chrome looks really nice and usable! I am using it in google chrome but I have problem with hardware decoding. Moonlight says that hardware decoding is not available and fails back to CPU decoding even though "about://gpu" in chrome shows otherwise: https://imgur.com/a/9rp3k

I checked this issue and it seems that chrome is reporting that it is supported but actually it is not - however there is patch for chromium which enables acceleration.

I tried moonlight in chromium and several different builds but moonlight fails to find my PC everytime. Is there some kind of known restriction / missing feature in chromium that would crumble down moonlight compared to chrome? I thought it might be mdns issue, but using mdns browser extension in chromium I was able to find my PC. Also add host button does not work in chromium ( works fine in chrome on same machine ).

Can anybody reproduce this on Linux with chromium?

**Comment by raidancampbell** [comment]
first paragraph: more things than just `Video Decode: Hardware accelerated` are required.  For reference, [here's my `about://gpu`](https://www.dropbox.com/s/agmhnobkgt1m0eg/Screenshot%202016-09-02%2016.58.30.png?dl=0), and hardware acceleration is used for me.  This is very likely a hardware/driver problem: I suspect from your screenshot that the blacklisted rasterizer is the issue.  If I were to venture a guess, it seems that the Intel graphics drivers for your hardware in linux have bugs which prevent this from working.  You may be able to find a flag to force it on, but it was set off for a reason.

Moonlight was written with chrome in mind, and I'm not familiar enough with chromium vs chrome API differences to answer what the problem is.  Possibly some javascript console logs could shed some light on the issue, and it may be fixable.

**Comment by cgutman** [comment]
@lamiska what distro are you using? Discovery works fine for me on Fedora 24's Chromium package (currently 52.0.2743.116).

**Comment by raidancampbell** [comment]
No response after two months, closing.
