### ISSUE TITLE
Wrong keys sent to server

### ISSUE THREAD

**Issue by Sethorax** [moonlight-stream/moonlight-chrome#204]
I am using the latest version of Moonlight Chrome on Google Chrome 56.0.2924.87 (64-bit) on macOS 10.12 as the client and Windows 10 with Geforce Experience 3.3.0.95 and nVidia Driver 378.66

Everything is working fine except some keys are not correctly sent to the server.
For example (i am using a german QERTZ-Keyboard) when i press the ü-key on the client the server prints out an ß. Or when i press the ö-key the server prints out an ü.
And all Numpad-Keys (only the numbers, all other keys are sent correctly) are received as normal numbers.

i have also tested this on a Windows 10 client. The keys are sent normally there.

**Comment by kevincharm** [comment]
I made a fix for the numpad issue on macOS. Will test it on my other machines tomorrow before I make a PR though. If there are any owners/contributors reading; is there a way to detect what platform Moonlight is running on (specifically within `input.cpp`)? I'm unfamiliar with pnacl- it looks like I can't just check for a define?

**Comment by cgutman** [comment]
Interesting, numpad is working fine as-is for me on Linux. What's different about how numpad is working on macOS than Windows and Linux?

**Comment by GreatTeacherOni** [comment]
I've got the same issues as OP. I've got a german QERTZ layout (as seen here: https://en.wikipedia.org/wiki/German_keyboard_layout#/media/File:KB_Germany.svg).
My Numpad-Keys including numbers work perfectly. Although as OP mentioned following keys don't work correctly:

- "**ü**"-key wrongly prints "**ß**" and "shift+**ü**" prints "**?**"

- "**?**"-key wrongly prints "**-**" and "shift+**?**" prints "**_**"

- "**´**"-key (right to the "**?**"-key) wrongly prints "**+**"

- "**+**"-key (right to the "**ü**"-key) wrongly prints "**´**" 

- "**ö**"-key  (right to the "**L**"-key) wrongly prints "**ü**"

- "**#**"-key (right to the "**Ä**"-key) wrongly prints "**^**"

- "**^**"-key (accent character left to the "1"-key) wrongly prints "**ö**"


Is this due to GFE (is it different in a newer GFE version?) or can i change this somehow and if i can, how?

I use the portable moonlight-client (1.1.0) on Windows 10 Pro x64 and i am accessing a Windows 7 Pro x64 machine with Geforce Driver 381.65 & GFE 2.11.4.1 (those old drivers still work the best on my GTX 960).

Kind regards,
GTO
