### ISSUE TITLE
Security of host computer.

### ISSUE THREAD

**Issue by Tacklebait** [moonlight-stream/moonlight-chrome#248]
Is there a security risk with leaving the ports open that are suggested for running moonlight over the internet?

**Comment by devint1** [comment]
There's always some risk involved when a network service is exposed to the Internet. Clients would still need to pair for GameStream to work, but there are always opportunities for things like DoS and software exploits. Since the server software is proprietary, only NVIDIA has the power to repair any vulnerabilities.

Personally, I'd set my firewall to be more restrictive. I have a GNU/Linux router that whitelists IPs, but it wouldn't be overly difficult to set this up on other systems.

**Comment by Tacklebait** [comment]
I guess I could get a static up proxy and whitelist it's ip.  And use it to connect my clients.
