### ISSUE TITLE
NaCl deprecation in favor of WebAssembly

### ISSUE THREAD

**Issue by rage311** [moonlight-stream/moonlight-chrome#251]
Google recently announced the deprecation of (P)NaCl support in favor of WebAssembly in Q1 2018.  I just figured I'd put it on your radar, in case you hadn't seen it yet.

https://developer.chrome.com/native-client/migration

> Given the momentum of cross-browser WebAssembly support, we plan to focus our native code efforts on WebAssembly going forward and plan to remove support for PNaCl in Q1 2018 (except for Chrome Apps). We believe that the vibrant ecosystem around WebAssembly makes it a better fit for new and existing high-performance web apps and that usage of PNaCl is sufficiently low to warrant deprecation.
> 
> We also recently announced the deprecation Q1 2018 of Chrome Apps outside of ChromeOS.

**Comment by cgutman** [comment]
They've already deprecated Chrome Apps, so this isn't really news for us. There are no APIs in the pipeline to replace PPB_VideoDecoder, so it is not possible to port Moonlight to run with WebAssembly. We will have to go the native app route, likely dropping ChromeOS support in the process for Chromebooks that can't run Android apps yet.

https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

**Comment by Sawyer007** [comment]
I already stopped using the chrome app. While the picture seems smoother then SteamInhome or Moonlight java. The mouse gets very bad and control input delay starts happening. 

So my number one choice as for now is Steam with a teamviwer-VPN and if it wont work I will use java moonlight.

I however have to retest the chrome app on a Virtual Windows box running on QEMU/Xubuntu. There it seems that the mouse lag inst happening or is much less noticeable since most of the hardware apart of GPU is emulated, the mouse also.

**Comment by rage311** [comment]
> There are no APIs in the pipeline to replace PPB_VideoDecoder, so it is not possible to port Moonlight to run with WebAssembly.

That's unfortunate.  I was hoping the Chrome app would be a slick way to get moonlight running on my OpenBSD laptop, but the Chromium port isn't built with NaCl support by default.  And now, the hope for WebAssembly is no more.

I'll give the Java client a whirl and see how that goes.

**Comment by Jorys-Paulin** [comment]
It might be a stupid question, but why can't we port PPB_VideoDecoder into WebAssembly C++?
