### ISSUE TITLE
Cannot Open Ports 47889, 47999, 48000

### ISSUE THREAD

**Issue by sweetbam** [moonlight-stream/moonlight-chrome#261]
Hello, I have Gamestream working when both devices are connected to the same network, however when I attempt to stream to a device that is on a different network (over wifi) I get sound from the streaming computer, but just a black screen. I have forwarded all the ports required to TCP and UDP respectively. When testing if the ports where "open" using yougetsignal.com/tools/open-ports/ It shows that 47998,47999,48000 are all closed and only 48010 of the udp ports is open. Any suggestions? Thanks

**Comment by cgutman** [comment]
If you're getting sound, that means 47999, 48000, and 48010 are forwarded correctly.

Video is sent over UDP 47998. Are you sure you forwarded that correctly? Your title says 47889. Did you typo that on your router settings?

**Comment by sweetbam** [comment]
I checked again to make sure it wasnt a silly mistake, but everything seems to be typed in correctly. One thing I noticed after restarting my modem and router is that Geforce Experience is forwarding the UDP ports automatically. for example its labeled Gamestream and then has the udp port 47998-48398. then there is 47999-48399, 48000-48400, and 48010-48410... is this normal? could it be messing up because they are overlapping? Thanks for the help!

**Comment by androbourne** [comment]
External port scanners are not accurate. Don't relay on them. A lot of routers use port trigger instead of port forwarding which means the ports will appear as closed since they are not being used currently.

Right off the bat it sounds like you might have double NAT going on. Are you using a router in between you and modem? Or just using the modem?

Have you tried to use port forwarding instead of port trigger and visa versa?

Did you allowing the ports through the local windows firewall? <<<---- this is a big one.

And yes, if you are using the modem only, overlapping in policies can cause issues (most modems wont even allow you to add another policy if it overlaps with an existing one). Try to clean that up so there is no overlap.

**Comment by Serveurperso** [comment]
Same problem... Gamestreaming fail 1/2 to launch and ask to open UDP 47999 already open
