### ISSUE TITLE
Moonlight friend can't control?

### ISSUE THREAD

**Issue by LostGirl046** [moonlight-stream/moonlight-chrome#297]
Hi so first off, this is a great program and works smoothly for what potato internet some of us have, haha, s thanks for all your hard work. The main issue I'm having is my friend can connect all fine and dandy and even see my screen and any and all steam games he chooses but he can't control anything. Can't move the mouse or use his keyboard? He doesn't have a controller (wired) to connect to his computer, but he might be looking to get one. I don't him to get one though if it might not do much in the long run anyways. I've seen on reddit that friends can control the host's mouse anyways so I'm not sure what the problem is. Does he have to open his ports too? Or do something else? On a sidenote, is there also a way to disconnect from moonlight on the host's end? Lol because he managed to access another game and open it on my computer even though I closed everything down, plus he was able to see my entire desktop, not just the game. I don't want him to see me looking up midget porn or anything like that, so thanks!

**Comment by Jorys-Paulin** [comment]
Hey @LostGirl046,
- The client may be prevented from controlling your host because of an __antivirus installed on the host__ (this is to prevent hackers from gaining access to your computer).
- Moonlight is just a client, meaning __we are dependant to GeForce Experience__. A "kill switch" on the host __can only be implemented on that host__, meaning in GFE, Wich ___we can't do___.
- Gamestream __wasn't really meant for screen sharing__ (at least for the shield) and it assumes the client is used by the owner of the host, so GFE's way of __capturing games isn't perfect__. Maybe we can get ___an event when the requested game is launched___, meaning we're safe to show the host's screen, but ___I don't know if that's possible___.

**Comment by LostGirl046** [comment]
@Jorys-Paulin 
Ahh okay I see what you mean about the "kill switch" and the screen sharing, thanks. So if it is my antiviral that's blocking my friend, how would I go step-by-step to fix this issue? When I went to portforward I thought it would allow this since I technically gave permission through my firewall by using the port numbers this site provided? Also should I be using more port numbers? Because I've seen on reddit/steam that people are using additional codes besides those provided (though those might be outdated now that I think about it)

**Comment by Jorys-Paulin** [comment]
Hey @LostGirl046,
- Try again with your antivirus **totally disabled**. BTW did it alerted something while playing?
- Port forwarding **should work fine**, I don't think GFE would change them anything soon.
- The most ideal for game compatibility is for you to use **the same type of controller** because your friend's should be considerated as if it were **plugged right into your computer**.

**Comment by LostGirl046** [comment]
@Jorys-Paulin 
No I didn't receive an alert or anything but okay I'll try that out soon. And so to confirm, we both should be using controllers of the same kind?

**Comment by Jorys-Paulin** [comment]
@LostGirl046 Hopefully this will avoid compatibility issues with games.

**Comment by LostGirl046** [comment]
@Jorys-Paulin Thanks for all your help so far! I'm going to close down the thread and open up another if I have any other issues, hopefully it will work haha
