### ISSUE TITLE
debug stuttering/hiccups

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-chrome#315]
Any idication on how can I debug what's causing hiccups/ stuttering when streaming to my HP elitebook (i5 4200U + 16 RAM +SSD) connected via wifi ( ping 2ms 180Mbps Download/ 190 upload )?
And maybe find a possible fix?
It works flawlessly on the same wifi connection with Galaxy Note 4.
Thanks in advance.

**Comment by apoklyps3** [comment]
no indication on how to debug?

**Comment by cgutman** [comment]
There's no magic way to debug those sorts of problems. Some packets didn't make it from your host to Moonlight.

What have you tried so far?

**Comment by hifihedgehog** [comment]
I had the same problem but I found the cause and it was not packet loss as others have suggested, either. Because Moonlight is running within a Chrome session, other Chrome extensions are enabled and they can potentially interfere with the video streaming. It turns out if I have any of my ad-blocking and video downloading extensions enabled, Moonlight stutters incessantly. I simply disabled each extension one by one, and then the experience was buttery smooth and absolute perfection from that point on. I strongly suggest to the developers to recommend that users disable other Chrome extensions when streaming or the streaming experience could likely suffer.
