### ISSUE TITLE
Streaming over internet stopped wokring.

### ISSUE THREAD

**Issue by Cowpie321** [moonlight-stream/moonlight-chrome#340]
I had .73 for a long while and got it working to stream over the internet, just yesterday I updated to .74 and it stopped working, i troubleshot the same way I did with the older version, checked ports and everything and it wont work, i got fed up with it and went back to .73 and now THAT wont work. Any ideas or suggestions would be wonderful. Thank you!

**Comment by Zibbibbo** [comment]
Same problem for me, until some days ago it was working great and now i can't connect trought internet

**Comment by Zibbibbo** [comment]
Same problem for me, everything was fine until some days ago and then it stopped to work.

The cause was the last Win10 update (Falla Creator build 1709), for some reason after this update the windows firewall blocks moonlight over internet. I've just disabled windows firewall and now moonlight works again.

**Comment by Cowpie321** [comment]
Okay, Ill give that a shot. Thanks

**Comment by Jorys-Paulin** [comment]
Hey @Cowpie321, is your issue resolved? If so, you can close this issue, otherwise, we'll be here to help!
