### ISSUE TITLE
Crash while loading games

### ISSUE THREAD

**Issue by dmnc-net** [moonlight-stream/moonlight-chrome#359]
I have plenty of games installed on my system and due to I'm not able to remove them from the GFE and moonlight-chrome can't call Steam directly (as like as moonlight-embedded), I have to let them load.

- Game thumbnails are loading very slowly like on the dial without cache
- Something is wrong, maybe some game, maybe just a amount of simultaneous fetches, but everytime it crashes. Everytime I have to remove PC from the list and re-add it and then it is working even list is quickly loaded.
v0.7.4 (3157fb6)

**Comment by Jorys-Paulin** [comment]
@dmnc-net I suggest you do the following:
- Re-install completely Geforce Experience
- Re-install the chrome app

**Comment by dmnc-net** [comment]
@Jorys-Paulin ok, please what is the goal of this reinstalling? Any confirmed issue or this is just a blind strike like "did you tried to turn it off and on again"? I have this issue among several versions up to 1.8.2 and since the first occurence, I've reinstalled/updated Google Chrome several times and GFE Twice. So what next I shall reinstall?

**Comment by Jorys-Paulin** [comment]
@dmnc-net 
- I just said that because of personal experience: sometimes for me, Geforce Experience decides to "disable" the gamestream service without any solution other than re-installing to make it work again.
- To check if the service is alive, go to `http://<host-local-ip>:47989/serverinfo` with your web browser, you should see some text if it's alive.
