### ISSUE TITLE
Mouse keeps going to the middle of the screen

### ISSUE THREAD

**Issue by DjDarkAssassin** [moonlight-stream/moonlight-chrome#394]
Whenever I play an FPS or anything that has to do with aiming, wherever I look will go that direction a little bit then go back to the middle. Is there any fix?

**Comment by Jorys-Paulin** [comment]
@DjDarkAssassin Install the latest version of chrome 64.

**Comment by DjDarkAssassin** [comment]
Alright, Thank you, I will try that.

**Comment by Floraly** [comment]
Didn't work for me.
Android and iOS are working quiet well even over WiFi 5Ghz and AC but when I use my Laptop with Gigabit Ethernet cabled to the streaming Computer the Picture stuttering and mouse resetting to middle of the screen. All devices set to standard resolution 720p or 1080p with 60fps or 30fps. I checked MTU and set it correctly to get it to work.
Even the streaming over internet to Mobil devices are great! But on my Laptop with 4th gen Core i7 and 16 GB RAM and gigabit I have problems. I killed owl other processes running and only ran Chrome in latest version with no tab open only Moonlight. And I use Windows 10 business branch no feature updates.

**Comment by troniac** [comment]
@Jorys-Paulin yes I have all up to date. :(

**Comment by Floraly** [comment]
Before use on my Computer I have updated anything:
Chrome Version 64.0.3282.119 (Offizieller Build) (64-Bit)
Moonlight Release 0.8.2

Actually there is no difference between Beta and Official Release:
BETA: Version 64.0.3282.119 (Offizieller Build) beta (64-Bit)
RELEASE: Version 64.0.3282.119 (Offizieller Build) (64-Bit)

I dont experience any issues on iOS or Nexus 5 with Android 6 even with Wifi.

I will not try Java Version because its deprecated a long time now and Chrome Extension should be fast enough.

**Comment by HawaiianSnow** [comment]
Yea im also experiencing the mouse reset issue, i updated from novembers build since it no long worked for me, now it works fine however the mouse resets to center randomly

**Comment by U-siro** [comment]
+1

**Comment by cgutman** [comment]
@U-siro @HawaiianSnow and anyone else experiencing this issue: What OS are you using and which version of Chrome?

**Comment by U-siro** [comment]
63.0.3239.132, Win 10

**Comment by cgutman** [comment]
@U-siro You should update Chrome. 63 is out of date.

**Comment by Jorys-Paulin** [comment]
Le me know how it goes. For now, closing this issue
