### ISSUE TITLE
Xbox One S Wireless/Bluetooth Controller Guide Button

### ISSUE THREAD

**Issue by Purduecoz** [moonlight-stream/moonlight-chrome#422]
I can't seem to get the "new" Xbox One S Wireless/Bluetooth controller guide button to map properly when streaming with Moonlight's Chrome extension. It doesn't work with the controller plugged in via USB or with it paired via Bluetooth. I'm running Steam in Big Picture mode thru Moonlight and everything else works fine.  I have the latest version of Moonlight and GeForce Experience, as well as the most current firmware for my controller.  I also tested the PS4 controller's guide button functionality and it works as expected (setting the focus back to Steam). Thanks.

**Comment by Jorys-Paulin** [comment]
@Purduecoz Moonlight is relying on the [Gamepad API](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API) to handle controller (at least it should), so if you go to http://html5gamepad.com/ you'll see that no buttons are affected to the Xbox button. That is because it is already mapped to "Open the game bar" on Windows.

**Comment by Purduecoz** [comment]
@Jorys-Paulin Good to know, thanks for the link.  I had assumed this button could still be used since the Playstation button works (and since I'm on a Mac where the button has no functionality on the OS)

Thanks again.
