### ISSUE TITLE
Are there any plans to make the mouse more responsive?

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-chrome#425]
Not sure why Moonlight is advertised as low latency, but the mouse is laggy and not really optimal. It is playable, but not the best. Steam In-Home Streaming for example has a waaay better mouse latency, mostly near perfect.

**Comment by cgutman** [comment]
What's your client hardware and OS?

Moonlight Chrome can perform pretty badly on some hardware, even if that hardware can run Steam IHS okay. If Steam works better for you, use that. The Android, iOS, and Raspberry Pi Moonlight clients perform much better, hence the release notes for Moonlight Chrome saying the performance can be very poor depending on the hardware.

**Comment by makedir** [comment]
I tried both clients I have, a Core M Broadwell-Y tablet and my laptop which has a core i5-3317U both running Windows 10, both show the same mouse latency over Chrome Moonlight. Sadly I cant/want use Steam IHS, because it is just terrible programmed and is not working and the dev of it is a moron unfortunately. Had long email contact with him and he is unable to fix the bugs I reported. For example it is incompatible with World of Warcraft, then it crashes if you go window mode (alt+enter) or switch to desktop, and lots of other annoying bugs. Moonlight was my only hope, but it also has lots of issues, for example the mouse latency. Then also the keyboard layout is always US.

**Comment by makedir** [comment]
just tried the new qt windows client... TERRIBLE input lag, unplayable.... will this get better or fixed? totally not usable in this state.

**Comment by Jorys-Paulin** [comment]
@makedir It might be your hardware then, everyone is getting great performance on the new client. Maybe get on the discord and ask for help or just open an issue on [moonlight-qt](https://github.com/moonlight-stream/moonlight-qt/issues/new)

**Comment by makedir** [comment]
nope. totally zero chance it is my hardware. the mouse input lag is just terrible, not acceptable.

**Comment by Jorys-Paulin** [comment]
@makedir It might. But what bitrate are you using?

**Comment by makedir** [comment]
default... 20mbit. 1920 60fps.

**Comment by Jorys-Paulin** [comment]
@makedir Can you give us the logs? They are under your %temp% directory, they are named Moonlight-something.

**Comment by makedir** [comment]
[Moonlight-1533045072.log](https://github.com/moonlight-stream/moonlight-chrome/files/2245591/Moonlight-1533045072.log)

**Comment by Jorys-Paulin** [comment]
@makedir Thanks, the devs will examine the logs when they go online. We'll get back to you then ;)

**Comment by makedir** [comment]
5ghz 866mbit

**Comment by cgutman** [comment]
@makedir From your logs it looks like it chose HEVC on your hardware, which isn't optimal on Intel CPUs prior to Skylake. If you change the Video Codec to "Force H.264" in Moonlight settings, that should fix it.

There's an open issue to make Auto avoid HEVC on hybrid/software decoders: https://github.com/moonlight-stream/moonlight-qt/issues/14

**Comment by makedir** [comment]
No difference between 264 and 265, really bad input lag. You cant play games like this.

**Comment by Jorys-Paulin** [comment]
You'll need to wait for the next release which will fix this issue. It should be out in less

**Comment by makedir** [comment]
what? what issue? so whats the issue? cgutman said it's codec issue, I said it doesnt make a difference.

**Comment by Jorys-Paulin** [comment]
... and your issue should be gone at the next update.

**Comment by makedir** [comment]
am I speaking English? I want to know the origin of the issue.

**Comment by Jorys-Paulin** [comment]
@makedir Your hardware doesn't support HEVC codec, because it apparently is a hybrid/software decoder and there are problems with that. If you need more info, ask cgutman over on https://github.com/moonlight-stream/moonlight-qt/issues/14

**Comment by makedir** [comment]
scroll up, and read again, what I said. doesn't matter, if used 264 or 265. tested both, same input lag. plus my GTX970 in host supports 265 encode. and my client also supports 265 to decode.

**Comment by cgutman** [comment]
@makedir what's your client CPU and GPU? Still the same as the March 8 comment?

There's probably 2 issues here.

- https://github.com/moonlight-stream/moonlight-qt/issues/14 may affect you based on your client GPU. I'll need to know the GPU to confirm.
- Steam does client-side cursor rendering to make the mouse latency appear lower than the video stream actually is. Moonlight renders the mouse with the video like everything else. GameStream doesn't support client-side cursor rendering.

IMHO, client-side cursor rendering is a hack that works around the real issue of higher than desired video latency. It's really only helpful for certain types of games like RTS (or for RDP/VNC like usage) where the mouse is always visible and crucial to operation, and only helpful if video latency is already intolerably high. I would rather work on lowering the video latency, rather than spending time on a hack to make the "mouse wiggle" test look better while actual in-game performance is the same. But since GameStream doesn't support client-side cursor, it's a moot point anyway.

**Comment by makedir** [comment]
Client GPU is uhd630.

"IMHO, client-side cursor rendering is a hack that works around the real issue of higher than desired video latency. It's really only helpful for certain types of games like RTS" ... like World of Warcraft... it is unplayable with this input lag. Or any other game, where you click the UI the entire time, city builders, Age of Empires ect ...

**Comment by cgutman** [comment]
Thanks for the info. As you said before, your GPU should support HEVC just fine and isn't affected by https://github.com/moonlight-stream/moonlight-qt/issues/14.

I find Dragon Age II (which uses the mouse for commanding characters and casting spells) to be very playable on the various setups I've tried Moonlight Qt on (one of which has a UHD 620). Either there's some issue specific to your setup (some buffering taking place somewhere on your network or PC) or you're just more sensitive to the input latency.

There's nothing we can do here to implement client-side mouse rendering, since the GameStream protocol doesn't support it right now. Until GameStream supports that (if ever), we can't fix this.
