### ISSUE TITLE
Mic from Headset not working

### ISSUE THREAD

**Issue by larador23** [moonlight-stream/moonlight-chrome#449]
The gamestream works fine and also the Speakers on my USB Headset. But the microphone doesnt not work on Client. What can i do ?

**Comment by Jorys-Paulin** [comment]
@larador23 I don't think neither Gamestream nor Moonlight was meant to support audio input. Unless you use VirtualHere, you can't do anything for now.

**Comment by vdsbenoit** [comment]
My workaround was to use Skype + [VB audio cable](https://www.vb-audio.com/Cable). I call myself on the host computer and I pipe the incoming sound from the call into a virtual input device. 

Here is a quick procedure : 
1. Create 2 Skype accounts
2. Install VB audio cable on the host (the Gamestream computer) 
3. Install Skype for desktop on the host computer, log in and set it up in order to auto accept incoming calls from contacts and to use the virtual input as microphone.
4. Call the host device with another device
5. Enjoy your game

**Comment by frederikb96** [comment]
I use this [workaround to stream from Linux to Windows](https://github.com/moonlight-stream/moonlight-qt/issues/294#issuecomment-1662751353)
