### ISSUE TITLE
Windows key not being captured

### ISSUE THREAD

**Issue by Jorys-Paulin** [moonlight-stream/moonlight-chrome#455]
When I connect via Moonlight to **my other Windows 10 PC**, when I press the `Windows` key it gets registered **only by the client system** and not by the host system. That means not all keys are captured, as I've seen in other issues. One solution to avoid all of these problems would be to **forward all keys to the host** system except one, in Virtualbox the `Right Ctrl` key. It would be nice to **implement this as well** in Moonlight if it's possible.

**Comment by lambia** [comment]
Hi there! I'm one of the lots of people who did the same question over and over again. So I think this is a duplicate question, but I'll tell you what you know.

As already said Moonlight is an open-source piece-of-code to interact with nVidia GameStream ecosystem. So it will not implement any new or it's own feature since its raison d'être is "just" replicating what understood from the reverse engineering of nVidia proprietary software running on some specific devices (eg. nVidia Tablet Shield and so on) and porting it to as many devices as possible.

Clarified this, please keep in mind I'm not involved in this project so could be reasonable wait for more authoritative answers from the project keeper, otherwise you can use the search function to find similar questions and read something about it.

**Comment by Jorys-Paulin** [comment]
@lambia Yes, but from what I understood of the NaCl module is that it captures all keys and directly sends them to game stream for processing. Whether or not they get captured would need a debugging of the module, which is not talkative. I think the original Shield could support this feature, but I can't verify since I don't own one. I mostly think the module don't capture all keys, or is not allowed to, but I can't check on my own, since I'm not a C developer.

**Comment by lambia** [comment]
> I think the original Shield could support this feature

that's the point. it doesn't. you can't alt-tab, alt-f4, ctrl-alt-canc, ctrl-maiusc-esc or any winkey-shortcut.

**Comment by Jorys-Paulin** [comment]
@lambia Well that's a shame. That would be a great feature request for GFE thought....

**Comment by Jorys-Paulin** [comment]
@cgutman Is it just a GFE problem, or is Moonlight not properly capturing that key?

**Comment by Jorys-Paulin** [comment]
According to cgutman, the windows key is blocked bt GFE. Closing this issue
