### ISSUE TITLE
Pairing not supported

### ISSUE THREAD

**Issue by raidancampbell** [moonlight-stream/moonlight-chrome#6]
X.509 crypto seems to be required for the SSL verification.  The [jsrsasign](http://kjur.github.io/jsrsasign/) library looks to be a good candidate for supporting this on the javascript side.

**Comment by dead** [comment]
What you guys think about using curl and openssl to do the HTTP requests? Moonlight-embedded already do that in the libgamestream. Since both openssl and curl are already ported to nacl it is easy to use.

Already implemented a experimental code that works.
https://github.com/dead/moonlight-chrome

**Comment by raidancampbell** [comment]
Thanks a bunch for this. @cgutman and I are going to be looking into this the next couple days.  We think the final implementation should include a git submodule to webports (formerly known as naclports), to allow portable compilation: I currently can't compile it on OSX, because it's lacking `curl.h` from `libcurl-dev`

**Comment by dead** [comment]
Not sure if webports could be included as a sub module.
One thing I didn't like was that I had to mount a filesystem to curl load the certs. But now I found out that curl can load the cert from memory ([ref](https://curl.haxx.se/libcurl/c/cacertinmem.html)).

**Comment by dead** [comment]
You guys can download the the libraries in:
https://gsdview.appspot.com/webports/builds/ or https://gsdview.appspot.com/naclports/builds/
Open a sdk version > select a trunk -> packages and download openssl, curl and libz

**Comment by dead** [comment]
I'd like you guys to look a this: https://github.com/dead/moonlight-chrome/commit/c420db537306f68bed862a5ab31ce9bb8146fc3e
And the openssl+curl+zlib libraries are here: [ports.zip](https://github.com/moonlight-stream/moonlight-chrome/files/146399/ports.zip)

It's almost pairing... But I can't make CryptoJS decode the challenge response properly.
Maybe we should just create a wrapper around the openssl to expose it to JS rather than using a native javascript library.

**Comment by raidancampbell** [comment]
This seems to be working now, as far as I can tell
