### ISSUE TITLE
Low FPS when streaming (worse than Steam's)

### ISSUE THREAD

**Issue by fehbari** [moonlight-stream/moonlight-chrome#80]
Not sure if this is the right place to report it, but I'm consistently getting much lower FPS when streaming with Moonlight compared to Steam's own home streaming.

That's with a 15" MacBook Pro (i7 2.2 GHz, 16 GB of RAM, Iris Pro) as the client, and a gaming desktop as the server (i5-4670, 16 GB of RAM, 980 Ti). The server has a wired Ethernet connection to the router, and the client is connected through AC Wi-Fi.

In both cases I'm streaming 1080p with mostly default options (20 Mbps for Moonlight, "balanced" with "automatic" bandwidth for Steam) and 60 FPS. So far I've tried The Witcher 3 and Black Ops 3. With Moonlight the framerate looks quite choppy and I can easily tell it's fluctuating well below the desired 60 FPS, even though the server is running the game at stable 60 FPS. With Steam's home streaming, I get pretty stable 60 FPS with minimal drops below. Reducing graphics or resolution in the game doesn't help, neither does moving closer to the router.

I suspect hardware decoding on the client isn't working, as I get similar performance in Steam's solution when I disable hardware decoding there. Is there any way I can check if Moonlight is using hardware decoding properly? And in case it's not, any way to enable it?

If there are any logs for me to provide or any way to benchmark the performance, I'd be glad to help.

**Comment by raidancampbell** [comment]
@cgutman this feels similar to the low power rendering path bug discussed [here](https://bugs.chromium.org/p/chromium/issues/detail?id=601191).  Do you know what came of that?

I just tested on El Capitan, chrome 52.0.2743.82, 2.6GHz i7/8GB/650M.  Host is some AMD CPU/16GB/970.  Clients are connected over the internet, and I couldn't reproduce your issue.  My "Google Chrome Helper" CPU usage hovered around 28%.  What's the CPU usage for moonlight vs steam?  I thought that the software decoding fallback was disabled for some reason, but a large CPU difference may indicate otherwise.

Another option to help diagnose what's happening is to toggle (and toggle back once you're done!) the chrome flag `chrome://flags/#disable-accelerated-video-decode`.

**Comment by felipebari** [comment]
@raidancampbell Here are the results of my test.

Moonlight - accelerated-video-decode _Enabled_
![screen shot 2016-07-28 at 8 32 14 pm](https://cloud.githubusercontent.com/assets/3378355/17234970/ba5c6812-5513-11e6-8ffd-2d11bf6b9408.png)
Moonlight - accelerated-video-decode _Disabled_
![screen shot 2016-07-28 at 8 29 40 pm](https://cloud.githubusercontent.com/assets/3378355/17234976/c5601484-5513-11e6-976c-95c043f5df47.png)
Steam

![screen shot 2016-07-28 at 10 33 33 pm](https://cloud.githubusercontent.com/assets/3378355/17234984/e414909e-5513-11e6-9324-18ac5564f800.png)

Disabling hardware-accelerated video decode in the Chrome flags actually didn't seem to change anything in my stream (it was equally choppy, not more, not less), but it did increase CPU usage.

I'm also on El Capitan and Chrome 52.0.2743.82
